# Generated by Django 4.2.10 on 2024-03-09 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mymap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Oreum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oplace", models.CharField(max_length=300)),
                ("ourl", models.CharField(max_length=300)),
                (
                    "oname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mymap.stamp"
                    ),
                ),
            ],
        ),
    ]
