# Generated by Django 4.2.10 on 2024-03-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mymap", "0003_alter_oreum_oname"),
    ]

    operations = [
        migrations.AddField(
            model_name="oreum",
            name="ocontent",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
